version: '3.7'

services:
  app:
    build: .
    container_name: iperf_nexus_app
    restart: always
    ports:
      - "5000:5000"
      - "5201-5210:5201-5210/tcp"
      - "5201-5210:5201-5210/udp"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env

  redis:
    image: redis:alpine
    container_name: iperf_nexus_redis
    restart: always
    ports:
      - "6379:6379"
